name: Build with ESP-IDF and create Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 3
      matrix:
        SLEEP_MODE:
          - NO_SLEEP
          - DEEP_SLEEP
        EXAMPLE_POWER_SAVE_MODE:
          - EXAMPLE_POWER_SAVE_NONE
          - EXAMPLE_POWER_SAVE_MIN_MODEM
          - EXAMPLE_POWER_SAVE_MAX_MODEM
        include:
          - SLEEP_MODE: CONFIG_DEEP_SLEEP=y
            SLEEP_TIME: CONFIG_SLEEP_TIME=10
    permissions: write-all
    steps:
    - name: Change Owner of Container Working Directory
      run: sudo chown -R 1000:1001 .
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: get SHA
      id: vars
      run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: get Tag
      run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Copy Default sdkconfig file and remove matrix configurations
      run: |
        cp ./sender/sdkconfig.default ./sender/sdkconfig
        sed -i '/${{ matrix.SLEEP_MODE }}.*/d' ./sender/sdkconfig
        sed -i '/${{ matrix.SLEEP_TIME }}.*/d' ./sender/sdkconfig
        sed -i '/${{ matrix.EXAMPLE_POWER_SAVE_MODE }}.*/d' ./sender/sdkconfig
    - name: Set version number in config
      run: |
        sed -i 's/CONFIG_ESP_LOGGER_VERSION="not set"/CONFIG_ESP_LOGGER_VERSION="${{ env.TAG }}-${{ env.SHA }}-${{ matrix.SLEEP_MODE }}-${{ matrix.EXAMPLE_POWER_SAVE_MODE }}"/' ./sender/sdkconfig
        sed -i 's/CONFIG_ESP_LOGGER_VERSION="not set"/CONFIG_ESP_LOGGER_VERSION="${{ env.TAG }}-${{ env.SHA }}-${{ matrix.SLEEP_MODE }}-${{ matrix.EXAMPLE_POWER_SAVE_MODE }}"/' ./receiver/sdkconfig
    - name: Configure sdkconfig for different options
      run: |
        echo "CONFIG_${{ matrix.SLEEP_MODE }}=y" > ./sender/sdkconfig
        echo "CONFIG_${{ matrix.EXAMPLE_POWER_SAVE_MODE }}=y" > ./sender/sdkconfig
    - name: esp-idf build sender
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.1
        target: esp32c6
        path: './sender/'
    - name: esp-idf build receiver
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.1
        target: esp32c6
        path: './receiver/'
    - name: rename artifacts
      run: |
        cp ./sender/build/ESPNOWLogger.bin ./sender/build/sender-${{ matrix.SLEEP_MODE }}-${{ matrix.EXAMPLE_POWER_SAVE_MODE }}.bin
        cp ./receiver/build/ESPNOWLogger.bin ./receiver/build/receiver-${{ matrix.SLEEP_MODE }}-${{ matrix.EXAMPLE_POWER_SAVE_MODE }}.bin
    - name: release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.TAG }}-${{ env.SHA }}
        tag: ${{ env.TAG }}
        allow-updates: true
        body_file: CHANGELOG.md
        token: ${{ github.token }}
        artifacts: "./sender/build/sender-${{ matrix.SLEEP_MODE }}-${{ matrix.EXAMPLE_POWER_SAVE_MODE }}.bin,./receiver/build/sender-${{ matrix.SLEEP_MODE }}-${{ matrix.EXAMPLE_POWER_SAVE_MODE }}.bin"
