name: ESP-IDF Build Action
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.1
        target: esp32c6
        path: '.'
    - name: Store Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ESPNOWLogger.bin 
        path: |
          build/ESPNOWLogger.bin
