name: Build with ESP-IDF and create Release
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted
    permissions: write-all
    steps:
    - name: Change Owner of Container Working Directory
      run: sudo chown -R 1001:1001 .
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.1
        target: esp32c6
        path: '.'
    - name: version
      run: echo "::set-output name=version::$(cat version)"
      id: version
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/ESPNOWLogger.bin
        asset_name: ESPNOWLogger.bin
        asset_content_type: application/octet-stream
