name: Build with ESP-IDF and create Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: self-hosted
    permissions: write-all
    steps:
    - name: Change Owner of Container Working Directory
      run: sudo chown -R 1001:1001 .
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build sender
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.1
        target: esp32c6
        path: './sender/'
    - name: esp-idf build receiver
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.1
        target: esp32c6
        path: './receiver/'
    - name: get SHA
      id: vars
      run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
    - name: get Tag
      run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ env.TAG }}-${{ env.SHA }}
        tag_name: ${{ env.TAG }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact sender
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./sender/build/ESPNOWLogger.bin
        asset_name: sender.bin
        asset_content_type: application/octet-stream
    - name: upload linux artifact receiver
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./receiver/build/ESPNOWLogger.bin
        asset_name: receiver.bin
        asset_content_type: application/octet-stream